blank_issues_enabled: false
contact_links:
  - name: Questions and discussions
    url: https://github.com/yaroher/surrealdb.go.orm/discussions
    about: Please use Discussions for questions and ideas
